#subscript to execute trades based on the final trading execution signal generated by the strategies module

import alpaca_trade_api as trade_api
from alpaca_trade_api import REST
from alpaca.trading.client import TradingClient
from alpaca.trading.enums import OrderSide, TimeInForce
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.stream import TradingStream
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.requests import StockLatestQuoteRequest
from alpaca.data.timeframe import TimeFrame

#import necessary libraries to plot data
import sys
import os
from matplotlib import pyplot as plt
import plotly.express as px
import pandas as pd
import numpy as np
from conf import config
from datetime import datetime, timedelta
import pickle
import json as json
import trading.strategies as strategies
from trading.position_risk import get_positions
from trading.position_risk import analyze_portfolio_weights


api = trade_api.REST(config.API_Key, config.Secret_key, config.alpaca_base_URL)

# --- FIX PATH (since execution.py is in subfolder) ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import trading.strategies as strategies
from trading.position_risk import get_positions
from trading.position_risk import analyze_portfolio_weights

api = trade_api.REST(config.API_Key, config.Secret_key, config.alpaca_base_URL)

# --- FIX PATH (since execution.py is in subfolder) ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

#initialize trading client
trading_client = TradingClient(
    config.API_Key,
    config.Secret_key,
    paper=True  
)

# --- GET ACCOUNT INFO ---
account = trading_client.get_account()
portfolio_value = float(account.portfolio_value)
print(f"Portfolio Value: ${portfolio_value:.2f}")

data_client = StockHistoricalDataClient(
    config.API_Key,
    config.Secret_key
)

positions = get_positions(trading_client)
print("Current Positions:", positions)

# --- ANALYZE CURRENT PORTFOLIO WEIGHTS
current_weights = analyze_portfolio_weights(positions)
for pos in current_weights:
    print(f"{pos['symbol']}: {pos['weight']*100:.2f}%")
    if pos["warning"]:
        print("WARNING: Position exceeds 30% of portfolio!")

# --- MAP STATE NAMES ---
state_map = {
    "Up": "priorstate_up",
    "Down": "priorstate_down",
    "Steady": "priorstate_steady"
}

# --- KELLY FUNCTION ---
def kelly_fraction(markov_matrix, current_state, mu_dict, fraction=0.25):
    row = markov_matrix.loc[current_state]

    ER = 0.0
    ER2 = 0.0

    for state, prob in row.items():
        mu = mu_dict.get(state, 0.0)
        ER += prob * mu
        ER2 += prob * (mu ** 2)

    if ER2 == 0:
        return 0.0

    kelly_full = ER / ER2
    kelly_frac = fraction * kelly_full

    return max(0.0, min(kelly_frac, 1.0))

fraction = 0.25
tickers = ['AAPL', 'TSLA', 'NVDA']

for ticker in tickers:
    signals = strategies.signals[ticker]
    execution_signal = signals['final'].upper()
    markov_matrix = strategies.markov_matrices[ticker]
    returns = strategies.returns_series[ticker]
    states = strategies.state_series[ticker]

    # --- ALIGN RETURNS AND STATES ---
    common_index = returns.index.intersection(states.index)
    returns = returns.loc[common_index]
    states = states.loc[common_index]

    # --- DETERMINE EXECUTION SIGNAL ---
    print(f"{ticker} - SMA: {signals['sma']}, Markov: {signals['markov']}, LSTM: {signals['lstm']}, Final: {execution_signal}")

    # --- MAP CURRENT STATE ---
    current_state_raw = states.iloc[-1]
    current_state = state_map[current_state_raw]
    print(f"{ticker} - Current State: {current_state_raw}")

    # --- ESTIMATE CONDITIONAL RETURNS ---
    mu_up = returns[states == "Up"].mean()
    mu_down = returns[states == "Down"].mean()
    mu_steady = returns[states == "Steady"].mean()

    mu_dict = {
        "state_close_up": mu_up,
        "state_close_down": mu_down,
        "state_close_steady": mu_steady
    }

    # --- POSITION SIZE ---
    if execution_signal == "BUY":
        position_size = kelly_fraction(markov_matrix, current_state, mu_dict, fraction)
    elif execution_signal == "SELL":
        mu_dict_short = {k: -v for k, v in mu_dict.items()}
        position_size = kelly_fraction(markov_matrix, current_state, mu_dict_short, fraction)
    else:
        position_size = 0.0

    # --- GET PRICE ---
    quote = data_client.get_stock_latest_quote(StockLatestQuoteRequest(symbol_or_symbols=[ticker]))
    price = quote[ticker].ask_price
    print(f"{ticker} - Current Price: ${price:.2f}")

    # --- COMPUTE SHARES ---
    dollar_amount = position_size * portfolio_value
    shares = int(dollar_amount / price)
    print(f"{ticker} - Dollar Allocation: ${dollar_amount:.2f}, Shares: {shares}")

    # --- SIMULATE POST-TRADE PORTFOLIO ---
    current_positions = {p.symbol: float(p.market_value) for p in positions}
    if execution_signal == "BUY" and shares > 0:
        trade_value = shares * price
        current_positions[ticker] = current_positions.get(ticker, 0) + trade_value
        new_total_value = portfolio_value + trade_value
    else:
        new_total_value = portfolio_value
        trade_value = 0

    new_weights = {sym: val / new_total_value for sym, val in current_positions.items() if val > 0}
    max_weight = max(new_weights.values()) if new_weights else 0

    # --- ADJUST IF EXCEEDS 80% ---
    if max_weight > 0.8 and ticker in new_weights and new_weights[ticker] > 0.8:
        target_value = 0.8 * new_total_value
        current_value = current_positions[ticker]
        if current_value > target_value:
            excess_value = current_value - target_value
            excess_shares = int(excess_value / price)
            shares -= excess_shares
            if shares < 0:
                shares = 0
            # update simulation
            trade_value = shares * price
            current_positions[ticker] = current_positions.get(ticker, 0) - (excess_value - excess_shares * price) + trade_value  # approx
            new_weights[ticker] = current_positions[ticker] / new_total_value

    max_weight = max(new_weights.values()) if new_weights else 0
    print(f"{ticker} - Adjusted Shares: {shares}, Max Portfolio Weight: {max_weight:.2f}")

    # --- LOG TRADE (PAPER TRADING - NO REAL EXECUTION) ---
    if execution_signal == "BUY" and shares > 0:
        print(f"PAPER TRADE: Would BUY {shares} shares of {ticker}")
    elif execution_signal == "SELL":
        print(f"PAPER TRADE: Would SELL {shares} shares of {ticker}")
    else:
        print(f"No trade for {ticker}")

print("\n===== SIMULATED PORTFOLIO AFTER TRADES =====")
for sym, val in current_positions.items():
    weight = val / new_total_value
    print(f"{sym}: ${val:.2f} ({weight*100:.2f}%)")
    if weight > 0.8:
        print("WARNING: Position exceeds 80% of portfolio!")